# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20180517170341) do

  create_table "active_admin_comments", force: :cascade do |t|
    t.string "namespace"
    t.text "body"
    t.string "resource_type"
    t.integer "resource_id"
    t.string "author_type"
    t.integer "author_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["author_type", "author_id"], name: "index_active_admin_comments_on_author_type_and_author_id"
    t.index ["namespace"], name: "index_active_admin_comments_on_namespace"
    t.index ["resource_type", "resource_id"], name: "index_active_admin_comments_on_resource_type_and_resource_id"
  end

  create_table "admin_users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_admin_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_admin_users_on_reset_password_token", unique: true
  end

  create_table "feedbacks", force: :cascade do |t|
    t.text "data"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "players", force: :cascade do |t|
    t.integer "uid"
    t.string "name"
    t.integer "age"
    t.string "f_pt"
    t.string "contract_type"
    t.integer "salary"
    t.integer "appearance_fee"
    t.integer "unused_sub_fee"
    t.date "expires"
    t.string "offer_status"
    t.integer "new_wage"
    t.date "new_date"
    t.integer "waclg"
    t.integer "waclg_num"
    t.date "loan_expires"
    t.date "injured_on"
    t.string "injury"
    t.string "time_out"
    t.integer "condition"
    t.integer "mtc_shp"
    t.string "sharpness"
    t.string "player_status"
    t.date "dob"
    t.integer "nat"
    t.string "second_nat"
    t.integer "height"
    t.integer "weight"
    t.string "position"
    t.string "second_position"
    t.string "personality"
    t.string "media_handling"
    t.string "preferred_foot"
    t.string "left_foot"
    t.string "right_foot"
    t.string "morale"
    t.string "match_load"
    t.string "training_load"
    t.string "injury_susceptibility"
    t.string "overall_risk"
    t.string "workload"
    t.string "training_happiness"
    t.string "training_happiness_details"
    t.string "position_role"
    t.string "additional_focus"
    t.string "loan_status"
    t.string "on_loan_from"
    t.string "squad_status"
    t.string "transfer_status"
    t.string "strength"
    t.string "weakness"
    t.integer "value"
    t.integer "cor"
    t.integer "cro"
    t.integer "dri"
    t.integer "fin"
    t.integer "fir"
    t.integer "fre"
    t.integer "hea"
    t.integer "lon"
    t.integer "lth"
    t.integer "mar"
    t.integer "pas"
    t.integer "pen"
    t.float "tck"
    t.integer "tec"
    t.integer "agg"
    t.integer "ant"
    t.integer "bra"
    t.integer "cmp"
    t.integer "cnt"
    t.integer "dec"
    t.integer "det"
    t.integer "fla"
    t.integer "ldr"
    t.integer "otb"
    t.integer "pos"
    t.integer "tea"
    t.integer "vis"
    t.integer "wor"
    t.integer "acc"
    t.integer "agi"
    t.integer "bal"
    t.integer "jum"
    t.integer "pac"
    t.integer "sta"
    t.integer "str"
    t.integer "aer"
    t.integer "cmd"
    t.integer "com"
    t.integer "ecc"
    t.integer "han"
    t.integer "kic"
    t.integer "onevone"
    t.integer "ref"
    t.integer "rus"
    t.integer "pun"
    t.integer "thr"
    t.integer "ca"
    t.integer "pa"
    t.integer "cr"
    t.integer "hr"
    t.integer "wr"
    t.integer "yel"
    t.float "tgls_90"
    t.float "tcon_90"
    t.float "tck_r"
    t.integer "starts"
    t.integer "shutouts"
    t.float "shot_90"
    t.float "sht_90"
    t.integer "svt"
    t.integer "svp"
    t.integer "svh"
    t.integer "red"
    t.integer "pom"
    t.float "pts_gm"
    t.float "pen_r"
    t.integer "pas_perc"
    t.float "ps_a_90"
    t.integer "off"
    t.integer "mstks"
    t.integer "gl_mst"
    t.integer "last_gl"
    t.integer "last_c"
    t.integer "mins_gm"
    t.integer "mins"
    t.float "last_5_games"
    t.integer "k_tck"
    t.float "k_ps_90"
    t.integer "k_pas"
    t.integer "k_hdrs"
    t.float "int_90"
    t.integer "hdr_perc"
    t.float "hdrs_w_90"
    t.float "gls_90"
    t.float "all_90"
    t.integer "conc"
    t.integer "gls"
    t.integer "g_mis"
    t.integer "won"
    t.integer "lost"
    t.integer "d"
    t.float "gwin"
    t.integer "fa"
    t.integer "fls"
    t.float "drbpg"
    t.float "dist_90"
    t.float "cr_c_a"
    t.float "ch_c_90"
    t.float "av_rat"
    t.integer "mins_gl"
    t.float "asts_90"
    t.integer "ast"
    t.integer "apps"
    t.float "ps_c_90"
    t.float "sqd_rat"
    t.float "mtc_rat"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "squad_id"
    t.integer "pos_st"
    t.integer "pos_aml"
    t.integer "pos_amc"
    t.integer "pos_amr"
    t.integer "pos_ml"
    t.integer "pos_mc"
    t.integer "pos_mr"
    t.integer "pos_wbl"
    t.integer "pos_dm"
    t.integer "pos_wbr"
    t.integer "pos_dl"
    t.integer "pos_dc"
    t.integer "pos_dr"
    t.integer "pos_sw"
    t.integer "pos_gk"
    t.index ["squad_id"], name: "index_players_on_squad_id"
  end

  create_table "squad_data", force: :cascade do |t|
    t.text "load_squad_data"
    t.text "update_squad_data"
    t.integer "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_squad_data_on_user_id"
  end

  create_table "squad_dnas", force: :cascade do |t|
    t.integer "squad_id"
    t.float "cor_m"
    t.float "cro_m"
    t.float "dri_m"
    t.float "fin_m"
    t.float "fir_m"
    t.float "fre_m"
    t.float "hea_m"
    t.float "lon_m"
    t.float "lth_m"
    t.float "mar_m"
    t.float "pas_m"
    t.float "pen_m"
    t.float "tck_m"
    t.float "tec_m"
    t.float "agg_m"
    t.float "ant_m"
    t.float "bra_m"
    t.float "cmp_m"
    t.float "cnt_m"
    t.float "dec_m"
    t.float "det_m"
    t.float "fla_m"
    t.float "ldr_m"
    t.float "otb_m"
    t.float "pos_m"
    t.float "tea_m"
    t.float "vis_m"
    t.float "wor_m"
    t.float "acc_m"
    t.float "agi_m"
    t.float "bal_m"
    t.float "jum_m"
    t.float "nat_m"
    t.float "pac_m"
    t.float "sta_m"
    t.float "str_m"
    t.float "aer_m"
    t.float "cmd_m"
    t.float "com_m"
    t.float "ecc_m"
    t.float "han_m"
    t.float "kic_m"
    t.float "onevone_m"
    t.float "ref_m"
    t.float "rus_m"
    t.float "pun_m"
    t.float "thr_m"
    t.float "key_g_mis_h"
    t.float "key_shp_h"
    t.float "fir_g_mis_h"
    t.float "fir_shp_h"
    t.float "rot_g_mis_h"
    t.float "rot_shp_h"
    t.float "bac_g_mis_h"
    t.float "bac_shp_h"
    t.float "hot_g_mis_h"
    t.float "hot_shp_h"
    t.float "you_g_mis_h"
    t.float "you_shp_h"
    t.float "low_ris_h"
    t.float "nor_ris_h"
    t.float "inc_ris_h"
    t.float "hig_ris_h"
    t.float "ver_ris_h"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["squad_id"], name: "index_squad_dnas_on_squad_id"
  end

  create_table "squads", force: :cascade do |t|
    t.string "team_name"
    t.integer "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_squads_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "squad_data_id"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
    t.index ["squad_data_id"], name: "index_users_on_squad_data_id"
  end

end
