class CreatePlayers < ActiveRecord::Migration[5.1]
  def change
    create_table :players do |t|
      t.integer :uid
      t.string :name
      t.integer :age
      t.string :f_pt
      t.string :contract_type
      t.integer :salary
      t.integer :appearance_fee
      t.integer :unused_sub_fee
      t.date :expires
      t.string :offer_status
      t.integer :new_wage
      t.date :new_date
      t.integer :waclg
      t.integer :waclg_num
      t.date :loan_expires
      t.date :injured_on
      t.string :injury
      t.string :time_out
      t.integer :condition
      t.integer :mtc_shp
      t.string :sharpness
      t.string :player_status
      t.date :dob
      t.string :nat
      t.string :second_nat
      t.integer :height
      t.integer :weight
      t.string :position
      t.string :second_position
      t.string :personality
      t.string :media_handling
      t.string :preferred_foot
      t.string :left_foot
      t.string :right_foot
      t.string :morale
      t.string :match_load
      t.string :training_load
      t.string :injury_susceptibility
      t.string :overall_risk
      t.string :workload
      t.string :training_happiness
      t.string :training_happiness_details
      t.string :position_role
      t.string :additional_focus
      t.string :loan_status
      t.string :on_loan_from
      t.string :squad_status
      t.string :transfer_status
      t.string :strength
      t.string :weakness
      t.integer :value
      t.integer :cor
      t.integer :cro
      t.integer :dri
      t.integer :fin
      t.integer :fir
      t.integer :fre
      t.integer :hea
      t.integer :lon
      t.integer :lth
      t.integer :mar
      t.integer :pas
      t.integer :pen
      t.integer :tck
      t.integer :tec
      t.integer :agg
      t.integer :ant
      t.integer :bra
      t.integer :cmp
      t.integer :cnt
      t.integer :dec
      t.integer :det
      t.integer :fla
      t.integer :ldr
      t.integer :otb
      t.integer :pos
      t.integer :tea
      t.integer :vis
      t.integer :wor
      t.integer :acc
      t.integer :agi
      t.integer :bal
      t.integer :jum
      t.integer :nat
      t.integer :pac
      t.integer :sta
      t.integer :str
      t.integer :aer
      t.integer :cmd
      t.integer :com
      t.integer :ecc
      t.integer :han
      t.integer :kic
      t.integer :onevone
      t.integer :ref
      t.integer :rus
      t.integer :pun
      t.integer :thr
      t.integer :ca
      t.integer :pa
      t.integer :cr
      t.integer :hr
      t.integer :wr
      t.integer :yel
      t.float :tgls_90
      t.float :tcon_90
      t.float :tck
      t.float :tck_r
      t.integer :starts
      t.integer :shutouts
      t.float :shot_90
      t.float :sht_90
      t.integer :svt
      t.integer :svp
      t.integer :svh
      t.integer :red
      t.integer :pom
      t.float :pts_gm
      t.float :pen_r
      t.integer :pas_perc
      t.float :ps_a_90
      t.integer :off
      t.integer :mstks
      t.integer :gl_mst
      t.integer :last_gl
      t.integer :last_c
      t.integer :mins_gm
      t.integer :mins
      t.float :last_5_games
      t.integer :k_tck
      t.float :k_ps_90
      t.integer :k_pas
      t.integer :k_hdrs
      t.float :int_90
      t.integer :hdr_perc
      t.float :hdrs_w_90
      t.float :gls_90
      t.float :all_90
      t.integer :conc
      t.integer :gls
      t.integer :g_mis
      t.integer :won
      t.integer :lost
      t.integer :d
      t.float :gwin
      t.integer :fa
      t.integer :fls
      t.float :drbpg
      t.float :dist_90
      t.float :cr_c_a
      t.float :ch_c_90
      t.float :av_rat
      t.integer :mins_gl
      t.float :asts_90
      t.integer :ast
      t.integer :apps
      t.float :ps_c_90

      t.float :sqd_rat
      t.float :mtc_rat

      t.timestamps
    end
  end
end
